name: cat_tinder
description: "Tinder for cats"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cached_network_image: ^3.3.1
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  connectivity_plus: ^6.1.4
  drift: ^2.13.0
  sqflite: ^2.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.3

  drift_dev: ^2.13.0
  build_runner: ^2.4.9

flutter:
  assets:
    - assets/icon.png

  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true